set tabstop=4
set shiftwidth=2
set number
set noswapfile
set t_Co=256
colorscheme ayu
"let ayucolor="light"  " for light version of theme
""let ayucolor="mirage" " for mirage version of theme
let ayucolor="dark"   " for dark version of theme
syntax on
set cursorline
set visualbell